### ISSUE TITLE
Tennis.ipynb

### ISSUE THREAD

**Issue by dkal3** [Shubha-Manikarnike/Deep-Reinforcement-Learning---Collaboration-and-Competition#1]
Hello!!!
Excellent work!!
When I tried to execute the Tennis.ipynb with the first command I get an error.

command -> from unityagents import UnityEnvironment
error          -> ModuleNotFoundError: No module named 'unityagents'

So, where I have make a mistake? 
Where have I to save your project?

Thank you in advance!

**Comment by Shubha-Manikarnike** [comment]
Hello, 
Thanks.
You need to install unityagents using a pip install unityagents

**Comment by dkal3** [comment]
After pip install unityagents I receive this error

Collecting unityagents
  Using cached unityagents-0.4.0-py3-none-any.whl (72 kB)
Requirement already satisfied: pytest>=3.2.2 in c:\users\danae\anaconda3\lib\site-packages (from unityagents) (5.4.3)
Requirement already satisfied: numpy>=1.11.0 in c:\users\danae\anaconda3\lib\site-packages (from unityagents) (1.18.5)
Collecting grpcio==1.11.0
  Using cached grpcio-1.11.0.tar.gz (14.2 MB)
Requirement already satisfied: Pillow>=4.2.1 in c:\users\danae\anaconda3\lib\site-packages (from unityagents) (7.2.0)
Collecting protobuf==3.5.2
  Using cached protobuf-3.5.2-py2.py3-none-any.whl (388 kB)
Requirement already satisfied: pyyaml in c:\users\danae\anaconda3\lib\site-packages (from unityagents) (5.3.1)
Requirement already satisfied: jupyter in c:\users\danae\anaconda3\lib\site-packages (from unityagents) (1.0.0)
Processing c:\users\danae\appdata\local\pip\cache\wheels\9b\04\dd\7daf4150b6d9b12949298737de9431a324d4b797ffd63f526e\docopt-0.6.2-py2.py3-none-any.whl
Note: you may need to restart the kernel to use updated packages.
ERROR: Could not find a version that satisfies the requirement tensorflow==1.7.1 (from unityagents) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow==1.7.1 (from unityagents)
